{
 "title": "Dashboard",
 "tags": [ "prometheus" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "CPU - Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "CPU  Usage ( / 100% * Number of Core )",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_org_label_schema_group=\"monitoring\"}[6m])) * 100"
    }
   ]
  },
  {
   "title": "Health Check",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "aspnetcore_healthcheck_status*-1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(node_memory_MemFree_bytes)" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_org_label_schema_group=\"monitoring\"})"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{container_label_org_label_schema_group=\"monitoring\"}[6m]) * 100  )",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (container_memory_usage_bytes{container_label_org_label_schema_group=\"monitoring\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Scrape  Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "App Exception Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "app_exception_count", "legendFormat": "{{ job}}" }
   ]
  },
  { "title": "Message Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Pushed Messages Counter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "message_queue_rate_1m_sourcebasebeenvex",
     "legendFormat": "[{{ job}}] {{ action}}"
    }
   ]
  },
  {
   "title": "Tracedata Message Counter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "message_queue_rate_1m_tracedatatopic",
     "legendFormat": "[{{ job}}] {{type}}"
    }
   ]
  },
  {
   "title": "Searchdata Messages Counter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "message_queue_rate_1m_searchdatatopic",
     "legendFormat": "[{{ job}}] {{type}}"
    }
   ]
  },
  {
   "title": "Update Working Day Messages Counter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "message_queue_rate_1m_updateworkingdaytopic",
     "legendFormat": "[{{ job}}] {{type}}"
    }
   ]
  },
  { "title": "Thread - Allocate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Total number of threads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_num_threads", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Number of open handles",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_handles", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Process working set",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_working_set_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC Collection",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum[5m])) * 1000",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Total req/s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In progress (global)",
   "type": "stat",
   "description": "Across ALL controllers globally!",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_in_progress)" }
   ]
  },
  {
   "title": "HTTP requests code rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_received_total[1m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Request duration (controller-handled requests only)",
   "type": "heatmap",
   "description": "Does NOT include requests that were not mapped to an ASP.NET Core controller!",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket[3m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requests received by controller",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(controller) (rate(http_requests_received_total[1m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 71 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Time spent in HTTP requests",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(http_request_duration_seconds_sum[1m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP request latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 82 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP requests code counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "yaxes": [
    { "format": "requests" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (http_requests_received_total)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP requests counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "yaxes": [
    { "format": "requests" }
   ],
   "targets": [
    {
     "expr": "sum by(endpoint) (http_request_duration_seconds_count)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Throughput per destination address type and protocol",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(tzsp_observed_bytes_total{instance =~ \"$instances\", from =~ \"$from\", to =~ \"$to\", protocol =~ \"$protocol\"}[3m]) * 8) by (to_type, protocol)",
     "legendFormat": "{{to_type}}/{{protocol}}"
    }
   ]
  },
  {
   "title": "Prometheus Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_max_fds{job=\"prometheus\"}",
       "legendFormat": "Max"
      },
      {
       "expr": "process_open_fds{job=\"prometheus\"}",
       "legendFormat": "Open"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"prometheus\"}",
       "legendFormat": "RSS"
      },
      {
       "expr": "prometheus_local_storage_target_heap_size_bytes{job=\"prometheus\"}",
       "legendFormat": "Target heap size"
      },
      {
       "expr": "go_memstats_next_gc_bytes{job=\"prometheus\"}",
       "legendFormat": "Next GC"
      },
      {
       "expr": "go_memstats_alloc_bytes{job=\"prometheus\"}",
       "legendFormat": "Allocated"
      }
     ]
    },
    {
     "title": "Allocations",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 58 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"prometheus\"}[1m])",
       "legendFormat": "Allocated"
      }
     ]
    },
    {
     "title": "Samples Appended",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_samples_appended_total[1m])",
       "legendFormat": "Samples"
      }
     ]
    },
    {
     "title": "Head Time series",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "prometheus_tsdb_head_series", "legendFormat": "Time series" }
     ]
    },
    {
     "title": "Head Active Appenders",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_tsdb_head_active_appenders",
       "legendFormat": "Head Appenders"
      }
     ]
    },
    {
     "title": "Head Chunks Removed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_chunks_removed_total[1m])",
       "legendFormat": "Removed"
      }
     ]
    },
    {
     "title": "Head Chunks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "prometheus_tsdb_head_chunks", "legendFormat": "Chunks" }
     ]
    },
    {
     "title": "Head Chunks Created",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 72 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_chunks_created_total[1m])",
       "legendFormat": "Created"
      }
     ]
    },
    {
     "title": "Blocks Loaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "prometheus_tsdb_blocks_loaded", "legendFormat": "Blocks Loaded" }
     ]
    },
    {
     "title": "Head Time Range",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "dateTimeAsIso" }
     ],
     "targets": [
      { "expr": "prometheus_tsdb_head_min_time", "legendFormat": "Min" },
      { "expr": "time() * 1000", "legendFormat": "Now" },
      { "expr": "prometheus_tsdb_head_max_time", "legendFormat": "Max" }
     ]
    },
    {
     "title": "Head GC Time/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 79 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_gc_duration_seconds_sum[1m])",
       "legendFormat": "GC Time"
      }
     ]
    },
    {
     "title": "WAL Latencies",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 84 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_wal_fsync_duration_seconds_sum[1m]) / rate(prometheus_tsdb_wal_fsync_duration_seconds_count[1m])",
       "legendFormat": "Fsync Latency"
      },
      {
       "expr": "rate(prometheus_tsdb_wal_truncate_duration_seconds_sum[1m]) / rate(prometheus_tsdb_wal_truncate_duration_seconds_count[1m])",
       "legendFormat": "Truncate Latency"
      }
     ]
    },
    {
     "title": "TSDB Reloads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_reloads_total[10m])",
       "legendFormat": "Reloads"
      }
     ]
    },
    {
     "title": "TSDB Problems",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 86 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_wal_corruptions_total[10m])",
       "legendFormat": "WAL Corruptions"
      },
      {
       "expr": "rate(prometheus_tsdb_reloads_failures_total[10m])",
       "legendFormat": "Reload Failures"
      },
      {
       "expr": "rate(prometheus_tsdb_head_series_not_found[10m])",
       "legendFormat": "Head Series Not Found"
      },
      {
       "expr": "rate(prometheus_tsdb_compactions_failed_total[10m])",
       "legendFormat": "Compaction Failures"
      },
      {
       "expr": "rate(prometheus_tsdb_retention_cutoffs_failures_total[10m])",
       "legendFormat": "Retention Cutoff Failures"
      }
     ]
    },
    {
     "title": "Retention Cutoffs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 91 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_retention_cutoffs_total[10m])",
       "legendFormat": "Retention Cutoffs"
      }
     ]
    },
    {
     "title": "Compactions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compactions_total[10m])",
       "legendFormat": "Compactions"
      }
     ]
    },
    {
     "title": "Compaction Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 93 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compaction_duration_seconds_sum[10m])",
       "legendFormat": "Compaction Time"
      }
     ]
    },
    {
     "title": "Scrape Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 98 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_target_interval_length_seconds{quantile!=\"0.01\", quantile!=\"0.05\"}",
       "legendFormat": "{{quantile}} ({{interval}})"
      }
     ]
    },
    {
     "title": "First Compaction, Avg Chunk Samples",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compaction_chunk_samples_sum[10m]) / rate(prometheus_tsdb_compaction_chunk_samples_count[10m])",
       "legendFormat": "Chunk Samples"
      }
     ]
    },
    {
     "title": "Target Scrapes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 100 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_target_interval_length_seconds_count[5m])",
       "legendFormat": "{{ interval }}"
      }
     ]
    },
    {
     "title": "Evaluation time of rule groups",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 105 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_rule_group_duration_seconds_sum[1m])",
       "legendFormat": "Rule evaluation duration"
      }
     ]
    },
    {
     "title": "Query engine timings",
     "type": "graph",
     "description": "Time spent in each mode, per second",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 107 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds_sum[1m])",
       "legendFormat": "{{slice}}"
      }
     ]
    },
    {
     "title": "Rule group evaulation problems",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 107 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_rule_group_iterations_missed_total[1m])  ",
       "legendFormat": "Rule group missed"
      },
      {
       "expr": "rate(prometheus_rule_evaluation_failures_total[1m])",
       "legendFormat": "Rule evals failed"
      }
     ]
    }
   ]
  }
 ]
}